name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: Gi tHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      # To allow one action to create release
      contents: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          addDate: 'true'
          
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.environment }}"

      - name: Print Output2
        id: outputs
        run: echo "${{ steps.test-action.outputs.nextVersion }}"

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        if:
          '${{ steps.test-action.outputs.nextVersion !=
          steps.test-action.outputs.oldVersion }}'
        with:
          name: '${{ steps.test-action.outputs.nextVersion }}'
          tag: '${{ steps.test-action.outputs.nextVersion }}'
          prerelease: '${{ steps.test-action.outputs.prerelease }}'
          body: '${{ steps.changelog-ci.outputs.change-logs }}'

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        if:
          '${{ steps.test-action.outputs.nextVersion !=
          steps.test-action.outputs.oldVersion }}'
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: '${{ steps.test-action.outputs.nextVersion }}'
          prerelease: '${{ steps.test-action.outputs.prerelease }}'
          title: '${{ steps.test-action.outputs.nextVersion }}'
